### ISSUE TITLE
Delete keys from the dopesheet

### ISSUE THREAD

**Issue by adamearle** [SuddenDevelopment/animall-autokey#4]
### Whats being keyed and making trouble
1. Deselecting is forcing keying updates.
2. Deleting keys from the dope sheet is keying.
3. After the first selection has been initiated every selection afterward causes a keyframe.

### Deleting & Clearing
1. Deleting keys from the dope sheet doesn't rekey when autokey is turned on.
2. Deleting points from the viewer is "Clearing" the keyframe information. The keyframe should not be deleted but remain behind.

**Comment by SuddenDevelopment** [comment]
coevered in stop motion
